apiVersion: v1
kind: Service
metadata:
  name: ricc-data-studio
  labels:
    app: ricc-data-studio
spec:
  type: ClusterIP
  selector:
    app: ricc-data-studio
  ports:
    - port: 8501
      targetPort: 8501
      name: http
